chemistry = ["acids-and-bases",
"amino-acids",
"analytical-chemistry",
"atmospheric-chemistry",
"biological-chemistry",
"environmental-chemistry",
"food-chemistry",
"green-chemistry",
"histochemistry",
"inorganic-chemistry",
"marine-chemistry",
"medicinal-chemistry",
"neurochemistry",
"nuclear-chemistry",
"oenology",
"organic-chemistry",
"organometallic-chemistry",
"periodic-table-of-elements",
"photochemistry",
"physical-chemistry",
"polyatomic-ions",
"polymer-chemistry",
"radiochemistry",
"surface-chemistry",
"theoretical-chemistry"]

earth_science = ["biogeography",
"cartography",
"climatology",
"environmental-science",
"gemology",
"geobiology",
"geology",
"geomatics",
"geophysics",
"glaciology",
"hydrology",
"oceanography",
"paleontolgy",
"pedology"]

medicine = ["alternative-medicine",
"cardiology",
"clinical-laboratory-sciences",
"dentistry",
"dermatology",
"emergency-medicine",
"gastroenterology",
"geriatrics",
"gynaecology",
"health-computing",
"hematology",
"hepatology",
"infectious-disease",
"toxicology",
"music-therapy",
"nephrology",
"neurology",
"nursing",
"nutrition",
"obstetrics",
"occupational-therapy",
"occupational-toxicology",
"oncology",
"opthalmology",
"optometry",
"otolaryngology",
"pathophysiology",
"paediatrics",
"pharmaceutical-sciences",
"physical-fitness",
"physical-therapy",
"physiotherapy",
"podiatry",
"preventive-medicine",
"primary-care",
"psychiatry",
"public-health",
"pulmonology",
"radiology",
"rheumatology",
"surgery",
"traditional-medicine",
"urology",
"vetirinary-medicine"]

geometry = ["algebraic-geometry",
"topology",
"trigonometry"]

mathematical_analysis = ["complex-analysis", 
"fourier-analysis",
"real-analysis"]

probability = ["probability-theory"]

statistics = ["hypothesis-testing"]

anthropology = ["archaeology", 
"biological-anthropology",
"cultural-antrhopology",
"linguistic-anthropology",
"social-anthropology"]

business = ["advertising",
"insurance",
"international-marketing",
"marketing-research",
"sports-marketing"]

economics = ["agricultural-economics",
"applied-economics",
"behavioural-economics",
"consumer-economics",
"development-economics",
"ecological-economics",
"econometrics",
"energy-economics",
"environmental-economics",
"finance",
"growth-economics",
"industrial-organisation",
"information-economics",
"international-economics",
"labour-economics",
"law-and-economics",
"macroeconomics",
"managerial-economics",
"microeconomics",
"monetary-economics",
"neuroeconomics",
"public-economics",
"real-estate-economics",
"resource-economics",
"transport-economics",
"welfare-economics"]

geography = ["cultural-geography",
"development-geography",
"health-geography",
"historical-geography",
"language-geography",
"political-geography",
"population-geography",
"religion-geography",
"social-geography",
"tourism-geography",
"urban-geography"]

political_science = ["politics-of-canada",
"civics",
"colonialism",
"comparative-politics",
"european-studies",
"geopolitics",
"imperialism",
"international-organisations",
"international-relations",
"political-behaviour",
"political-culture",
"political-economy",
"political-history",
"political-philosophy",
"politics-of-the-united-states",
"public-policy",
"voting-behaviour"]

sociology = ["african-studies",
"applied-sociology",
"asian-studies",
"collective-behaviour",
"conflict-theory",
"criminology",
"cultural-sociology",
"environmental-sociology",
"ethnic-studies",
"gender-studies",
"immigration",
"interactionism",
"management",
"medical-sociology",
"middle-eastern-studies"
"north-american-studies",
"sexology",
"social-policy",
"social-theory",
"social-transformation",
"sociobiology",
"sociology-of-aging",
"sociology-of-religion",
"sociology-of-terrorism",
"sociology-of-the-body",
"sociology-of-the-family",
"urban-studies",
"victimology"]

world_geography = ["geography-of-africa",
"geography-of-asia",
"geography-of-australia",
"geography-of-central-america",
"geography-of-europe",
"geography-of-north-america",
"geography-of-south-america",
"world-capitals"]

art_history = ["art-of-africa",
"art-of-asia",
"art-of-europe",
"art-of-oceania",
"baroque-art",
"contemporary-art",
"medieval-art",
"neoclassical-art",
"prehistoric-art"]

dance = ["choreography",
"history-of-dance"]

english = ["linguistics",
"literature",
"vocabulary"]

film_and_tv = ["animation",
"film-criticism",
"film-theory",
"filmmaking",
"live-action"]

history = ["ancient-history",
"history-of-the-environment",
"history-of-africa",
"history-of-asia",
"history-of-australia",
"history-of-europe",
"history-of-iran",
"history-of-russia",
"history-of-the-americas",
"intellectual-history",
"military-history",
"modern-history",
"scientific-history",
"technological-history",
"urban-history",
"western-civilization"]

philosophy = ["applied-philosophy",
"ethics",
"history-of-philosophy",
"logic",
"metaphysics",
"social-and-political-philosophy",
"theology"]

theater = ["acting",
"directing",
"dramaturgy",
"history-of-theater",
"musical-theater",
"puppetry",
"stage-design"]

visual_arts = ["architecture",
"calligraphy",
"decorative-arts",
"drawing",
"fashion-design",
"game-design",
"graphic-design",
"mixed-media",
"painting",
"photography",
"printmaking",
"product-design",
"sculpture",
"studio-art",
"textile-design",
"typography",
"user-experience-design"]

languages = ["activities",
"adjectives",
"adverbs",
"animals",
"body-parts",
"classroom",
"clothing",
"colors",
"conjunctions",
"current-events",
"expressions",
"feelings-and-emotions",
"food-and-dining",
"greetings",
"health",
"home",
"nature-and-the-environment",
"numbers",
"past-participles",
"places",
"prepositions",
"professions",
"questions",
"science-and-technology",
"shopping",
"social-relationships",
"sports",
"tenses",
"time",
"verbs",
"vocabulary",
"weather-and-seasons"]
